"""Initial874 Migration

Revision ID: 7db261c49475
Revises: 0ab57eefea91
Create Date: 2019-03-02 12:50:53.082247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db261c49475'
down_revision = '0ab57eefea91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blogs_user_id_fkey', 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'name')
    op.drop_column('blogs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('blogs_user_id_fkey', 'blogs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
